# Generated by Django 4.0.1 on 2022-01-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_profilefield_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_text', models.CharField(blank=True, max_length=280, null=True, verbose_name='Tweet')),
                ('image_tweet', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilefield')),
            ],
        ),
    ]
