# Generated by Django 4.0.1 on 2022-01-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilefield_biography'),
        ('twitter', '0002_tweets_like_alter_tweets_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='accounts.ProfileField', verbose_name='Like'),
        ),
    ]
