# Generated by Django 4.0.1 on 2022-01-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profilefield_biography'),
        ('twitter', '0005_alter_comment_comment_author_alter_comment_tweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='tweets',
            name='like',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.tweets')),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilefield')),
            ],
        ),
    ]
