# Generated by Django 4.0.1 on 2022-01-08 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Location')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('joined_on', models.DateField(auto_now_add=True, verbose_name='Joined on')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Photo')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover Photo')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Username')),
            ],
        ),
    ]
