# Generated by Django 4.0.1 on 2022-01-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefield',
            name='biography',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Location'),
        ),
    ]
