# Generated by Django 4.0.1 on 2022-01-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilefield_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefield',
            name='biography',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Bio'),
        ),
    ]
