# Generated by Django 4.0.1 on 2022-01-17 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_followfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followfollowing',
            name='followers',
        ),
        migrations.AddField(
            model_name='followfollowing',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='user_follower', to='accounts.ProfileField'),
        ),
        migrations.AddField(
            model_name='followfollowing',
            name='main_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_user', to='accounts.profilefield', verbose_name='Main User'),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilefield',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='followfollowing',
            name='following',
        ),
        migrations.AddField(
            model_name='followfollowing',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='accounts.ProfileField'),
        ),
    ]
