# Generated by Django 4.0.1 on 2022-01-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_followfollowing_followers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowFollowing',
            new_name='FollowUnfollow',
        ),
    ]
